import numpy as np
import csv
import matplotlib.pyplot as plt

basedir = '/Users/tamarad/Documents/Astro/DES/Data/AGN/'
list_of_redshifts = 'crossList.txt'

example_mz = 'Example.mz'

def loadMarzResults(filepath):
    return np.genfromtxt(filepath,delimiter=',', skip_header=2, autostrip=True, names=True, dtype=None)


def writeMarzResults(filepath,output):
    header=['# Results generated by XXX for file [[RM_Quasars]] at 0/0/0000, 0:00:00 PM (JSON: "0000-00-00000:00:00.000Z") at version {{1.3.8}}',
            '# Redshift quality > 2 for 00 out of 00 targets, a success rate of  00.00',
            '#ID  ,  Name                 ,  RA      ,  DEC      ,  Mag  ,  Type             ,  AutoTID,  AutoTN                   ,  AutoZ  ,  AutoXCor,  FinTID,  FinTN                    ,  FinZ   ,  QOP,  Comment']
    f = open(filepath,'w')
    for k in range(len(header)):
        f.write(header[k]+'\n')

    for j in range(res.shape[0]):
        line=''
        for i in range(len(res[j])):
            if str(res[j][i])[0:2]=="b'":
                item = str(res[j][i])[2:-1]
            else:
                item = str(res[j][i])
            line+=item+' , '
        line=line[:-2]+'\n'
        f.write(line)
    #with open(filepath, 'w', newline='') as mzfile:
        #mzwriter = csv.writer(mzfile,delimiter='')
    #    for k in range(len(header)):
    #        f.write(header[k])
        #line=''
        #for i in range(len(output['ID'])):

        #for line in output:
        #    print(line)
        #    for item in line:
        #        print(item)
            #print(line[1,-1])
                #line+=output[key][i]+' , '
            #mzfile.writewrow(line)

    #numpy.savetxt(filepath, res)#, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ')

res = loadMarzResults(basedir+example_mz)

agnfile=open(basedir+list_of_redshifts,'r')
n=771
num=np.zeros(n)
id =np.zeros(n)
z  =np.zeros(n)

i=0
for line in agnfile:
    if i !=0:
        num[i-1]=line[0:4]
        id[i-1] =line[5:16]
        z[i-1]  =line[17:25]
    i+=1
for i in range(len(num)): numstr = str(num[i])#.format('i')
print(numstr)


#print(id)
#print(z)
#agnfile.readline()
#for line in agnfile:
#    print(line)
#agn = numpy.genfromtxt(basedir+list_of_redshifts,delimiter=' ', skip_header=1, autostrip=True, names=False, dtype=None)
#print(agn)

#new = res
#for




writeMarzResults(basedir+'test.mz',res)

#plt.plot(res['Mag'],res['FinZ'],'x')
#plt.show()
#f = open(basedir+list_of_redshifts,'r')

